# Remove the "-DSHOW_LOG_ERROR" to eliminate the
# verbose error logging messages generated by EZNet
CFLAGS=-g -std=gnu11 -fsanitize=address -Wall -Werror -DSHOW_LOG_ERROR

all: webserver echoclient




echoclient: echoclient.c
	$(CC) $(CFLAGS) -oechoclient echoclient.c -lbsd 

webserver: webserver.c eznet.o utils.o
	$(CC) $(CFLAGS) -owebserver webserver.c eznet.o utils.o -lbsd -lpthread

eznet.o: eznet.c eznet.h
	$(CC) -c $(CFLAGS) eznet.c

utils.o: utils.c utils.h
	$(CC) -c $(CFLAGS) utils.c


clean:
	rm webserver *.o
